version: '3'
services:
  db:
    container_name: db-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db-example
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - $PWD/db-mysql-data:/var/lib/mysql
    networks:
      the-network:
        ipv4_address: 10.5.0.5
  web:
    container_name: docker-project
    image: docker-project-img
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/db-example
    networks:
      the-network:
        ipv4_address: 10.5.0.6
    depends_on:
      - db
networks:
  the-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16